# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml
os: unstable
# CLOUD_STORAGE_ENCRYPT_FILE_KEY
max_jobs: 2
environment:
  matrix:
    - platform: x64

branches:
  only:
    - master
    - master-all

# cache:
#   - node_modules
#   - '%USERPROFILE%\.electron-gyp'
#   - '%USERPROFILE%\.node-gyp'

install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt ./dev-assets/cloud-storage-key.json.enc -secret %ENCRYPT_FILE_KEY%
  - cmd: appveyor-tools\secure-file -decrypt ./dev-assets/code-sign.p12.enc -secret %ENCRYPT_FILE_KEY%
  - cmd: appveyor-tools\secure-file -decrypt ./dev-assets/prod.env.enc -secret %ENCRYPT_FILE_KEY%

  - ps: Install-Product node 12.4.0 x64
  # - ps: Install-Product node 10 x64
  # - ps: Install-Product node ''
  # - ps: Install-Product node 10.15.3 x64
  - set CI=true
  # - npm install -g npm@latest
  - npm install

build: off

matrix:
  fast_finish: true

before_build:
  - node --version
  - npm --version

build_script:
  - npm run build-ci

test_script:
  - npm run test-ci

after_test:
  - npm run upload-ci
  # - npm run release-ci
# artifacts:
#   - path: build/*.exe
#     name: exe
#   - path: build/*.blockmap
#     name: blockmap
#   - path: build/*.zip
#     name: zip
#   - path: build/*.msi
#     name: msi
#   - path: build/*.yml
#     name: yml
# deploy:
#   release: "Current_CI_Build"
#   description: 'Release description'
#   provider: GitHub
#   auth_token:
#     secure: w086h7SsN4ZengkZWbBDWzE2wcX3yNc9lM9vS0d7KD7ED0OSuUeGTEakTvJQzOAH # your encrypted token from GitHub
#   artifact: exe, blockmap, zip, msi, yml
#   draft: true
#   prerelease: true
#   force_update: true
#   on:
#     APPVEYOR_REPO_TAG: false
